hostname = m5.amap.com, m5-zb.amap.com, oss.amap.com, sns.amap.com

host, amap-aos-info-nogw.amap.com, reject
host, free-aos-cdn-image.amap.com, reject
host-suffix, v.smtcdns.com, reject

# > AMDC 处理，仅匹配高德 UA
^http:\/\/amdc\.m\.taobao\.com\/amdc\/mobileDispatch \r\nUser-Agent: AMapiPhone.* url-and-header reject

# > 搜索营销组件
^https:\/\/m5\.amap\.com\/ws\/shield\/search_business\/process\/marketingOperationStructured\? url jsonjq-response-body 'delpaths([["data","commonMaterial"],["data","tipsOperationLocation"],["data","resourcePlacement"]])'

# > 搜索首页历史标签
^https:\/\/m5\.amap\.com\/ws\/shield\/search_poi\/homepage\? url jsonjq-response-body 'delpaths([["history_tags"]])'

# > 打车订单页弹窗
^https:\/\/m5-zb\.amap\.com\/ws\/sharedtrip\/taxi\/order_detail_car_tips\? url jsonjq-response-body 'delpaths([["data","carTips","data","popupInfo"]])'

# > 导航详情页 / 路线规划 / 地点详情页 / 搜索详情页 / 导航结束页
^https:\/\/m5\.amap\.com\/ws\/(?:shield\/search\/new_hotword\?|faas\/amap-navigation\/card-service-(?:car-end|route-plan)|shield\/search_poi\/tips_adv\?) url reject-dict
^https:\/\/oss\.amap\.com\/ws\/banner\/lists\/\? url reject-dict

# > 首页推广卡片 / 红点角标 / 右上角动图 / 搜索框热词 / 天气 / 消息横幅
^https:\/\/m5\.amap\.com\/ws\/(?:aos\/main\/page\/product\/list\?|faas\/amap-navigation\/(?:main-page-assets|main-page-location|ridewalk-end-fc)|(?:mapapi\/hint_text\/offline_data|message\/notice\/list|shield\/search\/new_hotword)|shield\/scene\/recommend\?|valueadded\/weather\/v2\?) url reject-dict
^https:\/\/sns\.amap\.com\/ws\/msgbox\/pull_mp\? url reject-dict

# > 打车页红点角标 / 弹窗 / 天气图标 / 推广卡片
^https:\/\/m5-zb\.amap\.com\/ws\/boss\/(?:order\/car\/king_toolbox_car_bubble|tips\/onscene_visual_optimization) url reject-dict

# > 高德页面净化脚本
^https:\/\/m5\.amap\.com\/ws\/(?:aos\/perception\/publicTravel\/beforeNavi\?|bus\/plan\/integrate\?|c3frontend\/af-(?:hotel|launch)\/page\/main\?|perception\/drive\/(?:routeInfo|routePlan)|shield\/search\/(?:common\/coupon\/info|poi\/detail)|shield\/search_bff\/hotword\?|shield\/search_poi\/(?:mps|search\/sp|sug|tips_operation_location)|faas\/amap-navigation\/(?:card-service-plan-home|main-page)|shield\/frogserver\/aocs\/updatable\/1\?|shield\/dsp\/profile\/index\/nodefaasv3\?|shield\/search\/nearbyrec_smart\?|valueadded\/alimama\/splash_screen\?) url script-response-body https://raw.githubusercontent.com/Runeston/script/refs/heads/main/amap.js

# > 打车页推广卡片 / 弹窗 / 红点角标 / 天气图标
^https:\/\/m5-zb\.amap\.com\/ws\/(?:boss\/(?:car\/order\/content_info|order_web\/friendly_information)|promotion-web\/resource(?:\/home)?\?) url script-response-body https://raw.githubusercontent.com/Runeston/script/refs/heads/main/amap.js
