[rewrite_local]
^https?:\/\/(?:grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.playerunite\.v1\.Player\/PlayViewUnite$ url script-response-body https://raw.githubusercontent.com/BiliUniverse/Redirect/beta/js/BiliBili.Redirect.response.beta.js

^https?:\/\/(?:grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.pgc\.gateway\.player\.v2\.PlayURL\/PlayView$ url script-response-body https://raw.githubusercontent.com/BiliUniverse/Redirect/beta/js/BiliBili.Redirect.response.beta.js

^https?:\/\/api\.bili(?:bili\.com|api\.net)\/pgc\/player\/(?:api|web)\/playurl(?:\/html5)?\? url script-response-body https://raw.githubusercontent.com/BiliUniverse/Redirect/beta/js/BiliBili.Redirect.response.beta.js

^https?:\/\/api\.bili(?:bili\.com|api\.net)\/pgc\/player\/web\/v2\/playurl\? url script-response-body https://raw.githubusercontent.com/BiliUniverse/Redirect/beta/js/BiliBili.Redirect.response.beta.js

[mitm]
hostname = app.bilibili.com, app.biliapi.net, api.bilibili.com, api.biliapi.net, grpc.biliapi.net