[filter_local]
HOST-WILDCARD,*pcdn*.biliapi.net,REJECT

[rewrite_local]
# 拦截搜索默认词、动态红点、IP 资源
^https:\/\/(?:(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.(?:interface\.v1\.Search\/Default|dynamic\.v1\.Dynamic\/DynRed)|app\.bilibili\.com\/x\/resource\/ip) url reject

# 我的页面处理
^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine url script-response-body https://raw.githubusercontent.com/Runeston/script/refs/heads/main/bilibili_json.js

# 去除热搜发现
^https?:\/\/app\.bilibili\.com\/x\/v2\/search\/square\? url script-response-body https://raw.githubusercontent.com/Runeston/script/main/bilibili.js

# 开屏 / 搜索 / 信息流处理
^https:\/\/app\.bilibili\.com\/x\/v2\/(?:splash|search\?|feed\/index) url script-response-body https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Bilibili/bilibili.helper.v2.js

# gRPC 处理
^https:\/\/grpc\.biliapi\.net\/(?:bilibili\.community\.service\.dm\.v1\.DM\/DmView|bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus|bilibili\.app\.(?:view|viewunite)\.v1\.View\/(?:View|ViewProgress)|bilibili\.main\.community\.reply\.v1\.Reply\/MainList|bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll|bilibili\.app\.dynamic\.v2\.Dynamic\/DynAll)$ url script-response-body https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Bilibili/bilibili.helper.js

[mitm]
hostname = app.bilibili.com, grpc.biliapi.net