[rewrite_local]
^https?:\/\/.+\.bilivideo\.com\/upgcxcode\/ url script-request-header https://github.com/BiliUniverse/Redirect/releases/download/v0.2.19/request.bundle.js

^https?:\/\/[adbcefxy0-9]+\.mcdn\.bilivideo\.cn(?::(?:8000|8082))?\/v1\/resource\/ url script-request-header https://github.com/BiliUniverse/Redirect/releases/download/v0.2.19/request.bundle.js

^https?:\/\/[adbcefxy0-9]+\.mcdn\.bilivideo\.cn(?::(?:4483|9102))?\/upgcxcode\/ url script-request-header https://github.com/BiliUniverse/Redirect/releases/download/v0.2.19/request.bundle.js

^https?:\/\/(.+):4480\/upgcxcode\/ url script-request-header https://github.com/BiliUniverse/Redirect/releases/download/v0.2.19/request.bundle.js

^https?:\/\/upos-(?:hz|bstar1)-mirrorakam\.akamaized\.net\/upgcxcode\/ url script-request-header https://github.com/BiliUniverse/Redirect/releases/download/v0.2.19/request.bundle.js

[mitm]
hostname = *.mcdn.bilivideo.cn, upos-sz-mirror*bstar1.bilivideo.com, upos-*-mirrorakam.akamaized.net