[rewrite_local]
^https?:\/\/api\.coolapk\.com\/v6\/(?:(?:main\/(?:init|indexV8)|dataList|feed\/(?:detail|replyList))(?:\?|$)|page\/dataList\?.*title=%E9%85) url script-response-body https://github.com/Runeston/script/raw/main/coolapk.js
^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch url reject-200

[mitm]
hostname = api.coolapk.com
