# > 酷安_去广告合集@ddgksf2013
^https?:\/\/api\.coolapk\.com\/v6\/(?:(?:main\/(?:init|indexV8)|dataList|feed\/(?:detail|replyList))(?:\?|$)|page\/dataList\?.*title=%E9%85) url script-response-body https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js

# > 酷安_屏蔽热词@ddgksf2013
^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch url reject-200

hostname =  api.coolapk.com
