[rewrite_local]
^https?:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html url script-response-body https://github.com/Runeston/script/raw/main/jd_price.js
^https?:\/\/apapia-sqk-weblogic\.manmanbuy\.com\/baoliao\/center\/menu$ url script-request-body https://github.com/Runeston/script/raw/main/jd_price.js

[mitm]
hostname = in.m.jd.com, lite-in.m.jd.com, apapia-sqk-weblogic.manmanbuy.com
