[rewrite_local]
^https?:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html url script-response-body https://raw.githubusercontent.com/Runeston/script/refs/heads/main/jd_price.js
^https?:\/\/apapia-sqk-weblogic\.manmanbuy\.com\/baoliao\/center\/menu$ url script-request-body https://raw.githubusercontent.com/Runeston/script/refs/heads/main/jd_price.js

[mitm]
hostname = in.m.jd.com, lite-in.m.jd.com, apapia-sqk-weblogic.manmanbuy.com
