[rewrite_local]
# > 启动页 / 侧边栏精简
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/system\/startup\? url jsonjq-response-body 'delpaths([["reskinConfig"],["sidebarExSquareStyle","moreList"],["sidebarExSquareStyle","topList"]]) | .sidebarExSquareStyle.commonlyUsedList |= map(select(.title == "设置" or .title == "历史记录" or .title == "草稿箱" or .title == "我的钱包" or .title == "小程序" or .title == "未成年人模式" or .title == "官方客服" or .title == "内容偏好" or .title == "离线模式" or .title == "稍后再看" or .title == "举报中心" or .title == "挂件"))'

# > 直播广场 Banner
^https:\/\/(?:apissl|az\d-live|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/live\/feed\/square\/refresh\? url jsonjq-response-body 'delpaths([["data","banners"]])'

# > 视频流广告
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/feed\/(?:selection|selectionFast)\? url jsonjq-response-body 'if (.feeds | type) == "array" then .feeds |= map(select(.ad | not)) else . end'

# > 个人主页推荐
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/user\/profile\/v2\? url jsonjq-response-body 'delpaths([["postRecommends"]])'

# > 私信顶部推荐
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/im\/wd\/top\/navigation\/getRecommendedSession\? url jsonjq-response-body 'delpaths([["data","operationRecommendationList"]])'

# > 右下角悬浮推广
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/nearby\/widget\/info\? url reject-dict

# > 任务中心上报
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/taskCenter\/task\/report\? url reject-dict

# > 广告接口
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/ad\/ url reject-dict

# > 直播卡片
^https:\/\/(?:apissl|az\d-api(?:-js|-idc)?)\.(?:gifshow|ksapisrv)\.com\/rest\/n\/live\/feed\/info\/simplelive\/card\? url reject-dict

[mitm]
hostname = apissl.gifshow.com, apissl.ksapisrv.com, az*-api.ksapisrv.com, az*-api-idc.ksapisrv.com, az*-api-js.gifshow.com, az*-live.ksapisrv.com