[filter_local]
HOST,credits.bz.mgtv.com,REJECT
HOST,credits2.bz.mgtv.com,REJECT
HOST,credits3.bz.mgtv.com,REJECT
HOST,dflow.bz.mgtv.com,REJECT
HOST,encounter.bz.mgtv.com,REJECT
HOST,floor.bz.mgtv.com,REJECT
HOST,layer.bz.mgtv.com,REJECT
HOST,mob.bz.mgtv.com,REJECT
HOST,rc-topic-api.bz.mgtv.com,REJECT
HOST,rprain.bz.mgtv.com,REJECT
HOST,rprain.log.mgtv.com,REJECT
HOST,vip.bz.mgtv.com,REJECT
HOST-SUFFIX,da.mgtv.com,REJECT

[rewrite_local]
^https:\/\/dc\.bz\.mgtv\.com\/dynamic\/v\d\/skin\/config\? url reject-dict
^https:\/\/dc\.bz\.mgtv\.com\/dynamic\/v\d\/channel\/ads\? url reject-dict
^http:\/\/mobileso\.bz\.mgtv\.com\/spotlight\/search\/v\d\? url reject-dict
^https:\/\/damang\.api\.mgtv\.com\/station\/album\/red\/dot\? url reject-dict
^https:\/\/hb-boom\.api\.mgtv\.com\/release\/pullReleaseInfo$ url reject-dict
^https:\/\/mobile\.api\.mgtv\.com\/v\d\/mobile\/checkUpdate\? url reject-dict
^https?:\/\/mobileso\.bz\.mgtv\.com\/mobile\/recommend\/v\d\? url reject-dict


[mitm]
hostname = dc?.bz.mgtv.com, mobileso.bz.mgtv.com, damang.api.mgtv.com, hb-boom.api.mgtv.com, mobile.api.mgtv.com, mobile.api.hunantv.com, me.bz.mgtv.com, mobile-thor.api.mgtv.com
