[rewrite_local]
^https?:\/\/h5\.if\.qidian\.com\/argus\/api\/v1\/user\/getlogininfo url script-response-body https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/QDReader/qdreader.js

[mitm]
hostname = h5.if.qidian.com